- src/App.css
- src/Page/Home.tsx
- src/Router/routes.tsx
- src/assets/Css/tailwind.css
- tailwind.config.js
> [chore] 기본 컬러 성정 및 router 수정

- .gitignore
- src/Page/Recruitment.tsx
- src/Router/routes.tsx
- src/Utils/apiFetch.ts
폴더 구조 변경 및 페이지 추가
- routes.tsx
모집글 도메인 추가
- Recruitment.tsx
모집 글 페이지 생성
- Utils
공통 함수 폴더 생성
- components
컴포넌트 폴더 파일 추가
> Feat/folder 구조 변경 및 페이지 추가

- src/App.css
- src/Component/a.html
App.css 수정 및 Compnent 폴더 생성
-  App.css
- Compnent
> [chore] App.css 수정 및 Compnent 폴더 생성

- src/Components/SignUpForm.tsx
- src/Page/SignUp.tsx
회원가입 컴포넌트 구현 및 페이지에서 분리
- src/Components/SignUpForm.tsx
SignUpForm 구현 
- src/Page/SignUp.tsx
페이지에서 SignUpForm 컴포넌트 import
> [feat] 회원가입 컴포넌트 구현

- package-lock.json
- package.json
- src/App.tsx
- src/Hooks/useLocalStorage.tsx
useLocalStorage undefined 에러 수정
- useLocalStorage
처음 localStorage 호출 시 값이 없어 undefined가 출력되어 parse가 안되는 문제 해결
> [fix] useLocalStorage

- src/Components/SignUpForm.tsx
Api fetchCall 방식으로 수정
- src/Components/SignUpForm.tsx
axios -> fetchCall 방식으로 수정 및 ApiResponse 타입 추가
> [refactor] : SignUpForm 컴포넌트 fetchCall 방식으로 수정

- src/Components/SignInForm.tsx
SignInForm 컴포넌트 fetchCall 방식으로 수정
- src/Components/SignInForm.tsx
axios-> fetchCall 방식으로 수정 및 LoginResponse 타입 추가.
LocalStorage에 유저정보 저장 기능 추가.
profileCheck false인 경우 navigate url 변경.
> [refactor] : SignInForm 컴포넌트 fetchCall 방식으로 수정

- src/Components/Common/Header.tsx
- src/mocks/userHandlers.ts
Header로고에 메인페이지 바로가기 추가
- Header.tsx
Header로고에 메인페이지 바로가기 추가
> [feat] header 로고에 to={"/"} 링크 추가

- src/Components/Mypage/Profile.tsx
- Profile.tsx
fetchCall import로 변경
> [feat] 마이페이지 프로필 조회 api 연동

- src/Components/SignInForm.tsx
- src/Components/SignUpForm.tsx
[fix] 로그인 회원가입 response 수정
- sigIn signUp 수정
로그인, 회원 가입 수정
> [fix] 로그인 회원가입 response 수정

- src/App.tsx
- src/Components/SignInForm.tsx
- src/Components/SignUpForm.tsx
- src/Page/MyPage.tsx
- src/Utils/apiFetch.ts
- src/mocks/mockData.ts
- src/mocks/userHandlers.ts
- vite.config.ts
> [fix] Mock API Test 결과 수정

- src/App.tsx
- src/Page/Recruitment.tsx
- src/Router/routes.tsx
[fix] URL에 Header 따른 해더 변경
- App.tsx
useLocation 제거
- Routes.tsx
useLocation 추가
> [fix] URL에 Header 따른 해더 변경

- src/Components/SignInForm.tsx
로그인 응답 타입 정의 및 데이터 구조 단순화
- src/Components/SignInForm.tsx
access 타입 정의 및 응답 데이터 구조 개선
> [refactor]: 로그인 응답 타입 정의 및 데이터 구조 단순화

- src/Components/SignUpForm.tsx
회원가입 제출 데이터 타입 추가
- src/Components/SignUpForm.tsx
회원가입 제출 데이터 타입 추가 및 응답 데이터 구조 개선
> [refactor] : 회원가입 제출 데이터 타입 추가

- src/Components/Common/SelectBox.tsx
- src/Page/Recruitment.tsx
- src/assets/icons/arrow_drop_down.svg
- src/assets/icons/arrow_drop_up.svg
메인 페이지 데이터 필터링을 위한 선택 박스 생상
- src/Components/Common/SelectBox.tsx
선택 박스 컴포넌트 
interface SelectBoxProps {
options: string[]; // option 값들
selectedValue: string; // 선택된 값
onSelect: (value: string) => void; // 변경 함수
}
- src/assets/icons/arrow_drop_down.svg
- src/assets/icons/arrow_drop_upsvg
drop 관련 이미지 추가
> [feat] Select Box 컴포넌트 생성

- src/Components/SignUpForm.tsx
전화번호 입력값 하이픈 필수 추가로 정정
- src/Components/SignUpForm.tsx
전화번호 타입 하이픈 필수 추가로 정정
placeholder 내용 정정 및 maxLength 값 추가
> [refactor] : 전화번호 입력값 하이픈 필수 추가로 정정

- src/mocks/mockData.ts
- src/mocks/profileHandlers.ts
- src/mocks/userHandlers.ts
[fix] 프로필 생성 후 유저 profileCheck 값 변경 및 mockData type 설정
- src/mocks/mockData.ts
interface를 통한 type 설정
- src/mocks/profileHandlers.ts
프로필 수정 후 user의 profileCheck 수정
> [fix] 프로필 생성 후 유저 profileCheck 값 변경 및 mockData type 설정

- src/mocks/profileHandlers.ts
- src/mocks/userHandlers.ts
[fix] userHandler URL 수정 및 프로필 생성 시 local 저장 부분 수정
- src/mocks/profileHandlers.ts
local 저장 값 String으로 변환
- src/mocks/userHandlers.ts
URL 수정
> [fix] userHandler URL 수정 및 프로필 생성 시 local 저장 부분 수정

- src/Components/Mypage/MyAccountSettings.tsx
- src/Components/Mypage/SideComponents/DeleteAccountModal.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/Components/Mypage/SideComponents/PasswordChangeModal.tsx
- tsconfig.app.json
회원탈퇴 모달 추가, 기존 비밀번호 입력 레이아웃 추가
- DeleteAccountModal
회원탈퇴 모달 추가
- PasswordChangeModal
기존 비밀번호 입력 레이아웃 추가
> [layout] 회원탈퇴 모달 추가, 기존 비밀번호 입력 레이아웃 추가

- package-lock.json
- package.json
- src/Components/Layout/ProfileRequiredRoutes.tsx
- src/Components/Mypage/Profile.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/SideComponents/CountryName.tsx
- src/Components/Mypage/SideComponents/MyLang.tsx
- src/mocks/userHandlers.ts
Mypage 기능 수정 및 개발
- Profile.tsx
로컬에서 프로필 체크 확인 후 false면 프로필 수정페이지로 강제 이동
- ProfileEdit.tsx
닉네임 중복검사, 리랜더링 방지, profileData 초기값 설정
- userHandler.tsx
response data 수정
> [Feat] Mypage 기능 수정 및 개발

- src/Components/Common/Header.tsx
- src/Components/Mypage/Profile.tsx
- src/Components/SignInForm.tsx
- src/Components/SignUpForm.tsx
- src/Utils/apiFetch.ts
- src/main.tsx
- src/mocks/userHandlers.ts
로그아웃 오류 수정 및 baseURL 설정
- src/Components/Common/Header.tsx
로그아웃 시 페이지 이동 설정
불필요한 코드 삭제
- src/mocks/userHandlers.ts
로그아웃 성공 시 데이터 반환
> [fix] 로그아웃 오류 수정

- src/Page/SignIn.tsx
로고 추가 및 홈 링크 연결
- 로그인 박스 위에 '여행족' 로고 텍스트 추가
- Link 컴포넌트 사용하여 홈('/')으로 이동하는 링크 구현
> [feat] : 로고 추가 및 홈 링크 연결

- package-lock.json
- package.json
- src/Components/Mypage/Profile.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/mocks/mockData.ts
- src/mocks/userHandlers.ts
- ProfileEdit.tsx
multi selectbox 기능
- EmailChangeModal.tsx
이메일 유효성 검사 및 이메일 변경 기능 구현
> [Feat] 이메일 변경 기능, 이메일 유효성 검사, multi selectbox 기능 추가

- src/Components/Common/SelectBox.tsx
- src/Components/Recruitment/SearchBar.tsx
- src/Page/Recruitment.tsx
- src/mocks/mockData.ts
- src/mocks/recruitHandlers.ts
recruit Page Post 생성
- src/Components/Recruitment/SearchBar.tsx
검색 컴포넌트 생성
- src/Page/Recruitment.tsx
Post 생성 (컴포넌트 분리 x)
> [feat] recruit Page Post 생성

- src/Components/Layout/index.tsx
- src/Components/Mypage/Profile.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/test/MyRecruitTest.tsx
- src/Components/Mypage/test/MypageTest.tsx
- src/Components/Mypage/test/SidebarTest.tsx
- src/Router/routes.tsx
- tailwind.config.js
마이페이지 새로운 UI 테스트
- MypageTest, MyRecruitTest, SidebarTest
마이페이지 새로운 UI 테스트
> [test] 마이페이지 새로운 UI 테스트

- src/Components/Common/Header.tsx
- src/Components/Common/Post.tsx
- src/Components/Common/SelectBox.tsx
- src/Components/Mypage/SideComponents/DeleteAccountModal.tsx
- src/Components/Recruitment/SearchBar.tsx
- src/Components/SignInForm.tsx
- src/Constants/localKey.ts
- src/Page/Recruitment.tsx
- src/Page/Review.tsx
- src/Utils/apiFetch.ts
- 작업 중 pull로 인한 코드 충돌
- src/Components/Common/Header.tsx
디자인 수정 및 import 변경
-src/Components/Common/Post.tsx
recruit Post 분리
> [chore] 출동 해결 commit

- src/Components/Common/Header.tsx
- src/Components/Common/SelectBox.tsx
- src/Components/Layout/HomeLayout.tsx
- src/Constants/MBTI.ts
[feat] MBTI 선택 창 및 글 작성 버튼 생성
- src/Components/Layout/HomeLayout.tsx
MBTI 선택 버튼 생성 (user mbti 정보는 불러오지 않음 -> 추후 연동)
MBTI 정보를 저장해야 하는데, 이러면 유저 정보를 불러오는 구간이 좀 많은 것 같습니다
이를 보관하고 사용하는 방법에 대해 서로 생각해보면 좋을 것 같습니다.
> [feat] MBTI 선택 창 및 글 작성 버튼 생성

- src/Components/RecruitPost/EditBtn.tsx
- src/Components/RecruitPost/JoinBtn.tsx
- src/Page/RecruitPost.tsx
버튼 컴포넌트 분리 및 수정하기 버튼 권한 설정
- src/Components/RecruitPost/EditBtn.tsx
작성자 ID와 유저 ID가 같을 경우에만 수정하기 버튼 보여줌
- src/Components/RecruitPost/JoinBtn.tsx
참여하기 요청 및 결제준비 요청 구조 구현, 추후 handler와 연결 및 수정 예정
- src/Page/RecruitPost.tsx
버튼 컴포넌트로 분리
> [feat] : 버튼 컴포넌트 분리

- src/Components/Mypage/MyCompletedTrips.tsx
- src/mocks/handlers.ts
- src/mocks/mockData.ts
- src/mocks/participationHandlers.ts
- mockData, participationHandler
참여 API 및 mockData 초기 설정
> [Feat] 참여 API 및 Mock 데이터 초기 설정

- src/Components/Common/Post.tsx
- src/Components/RecruitPost/Buttons/EditBtn.tsx
- src/Components/RecruitWrite/BasicInfo/DestinationSelect.tsx
- src/Components/RecruitWrite/BasicInfo/RegionInput.tsx
- src/Components/RecruitWrite/BasicInfo/TravelDateSelect.tsx
- src/Components/RecruitWrite/Btns.tsx
- src/Components/RecruitWrite/ExpectMoney.tsx
- src/Components/RecruitWrite/Preview.tsx
- src/Components/RecruitWrite/SpecificLocationSearch.tsx
- src/Components/RecruitWrite/TravelPlan.tsx
- src/Page/RecruitPost.tsx
- src/Page/Recruitment.tsx
- src/mocks/mockData.ts
- src/store/recruitPostStore.ts
- 글 수정하기 관련 useEffect  추
- 글 수정하기 기능 추가
- src/Components/RecruitPost/Buttons/EditBtn.tsx
- src/Page/RecruitPost.tsx
수정하기 버튼 기능 연동
- src/Components/RecruitWrite/BasicInfo/DestinationSelect.tsx
- src/Components/RecruitWrite/BasicInfo/RegionInput.tsx
- src/Components/RecruitWrite/TravelPlan.tsx
수정하기 관련 useEffect로 값 설정
- src/Components/RecruitWrite/BasicInfo/TravelDateSelect.tsx
년도 선택 옵션 수정 (수정하기 시 입력된 년도부터 내년까지)
- src/Components/RecruitWrite/Btns.tsx
수정하기와 등록하기 기능 구분
- src/Components/RecruitWrite/ExpectMoney.tsx
단위 구분을 위한 , 추가
> [refactor] 모집 글 등록 수정

- package-lock.json
- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Rating.tsx
- src/mocks/participationHandlers.ts
- src/store/profileStore.ts
- profileStore
프로필 전역상태관리 (zustand사용)
- MyCompletedTrips, Rating
여행 평점을 위한 참여 조회 구현
> [feat][refactor] 참여 조회 기능 구현 및 프로필 전역상태관리(zustand)

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Rating.tsx
- src/mocks/handlers.ts
- src/mocks/ratingHandler.ts
- src/store/profileStore.ts
- ratingHandler, Rating
평점 작성 구현 및 api 구성
- profileStore
api 호출 함수 추가
> [feat] 평점 작성 구현 및 api 구성 및 api 호출 함수 추가

- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/mocks/handlers.ts
- src/mocks/mockData.ts
- src/mocks/participationHandlers.ts
- src/mocks/paymentHandlers.ts
> [fix] 참여 충돌 수정

- src/Components/ReviewWrite/RecruitInfo.tsx
- src/Components/ReviewWrite/ReviewInput.tsx
- src/Page/ReviewForm.tsx
- src/Router/routes.tsx
- src/mocks/mockData.ts
- src/store/reviewStore.ts
후기 작성 기능 구현
- src/Components/ReviewWrite/RecruitInfo.tsx
모집글 내용 불러오는 기능
- src/Components/ReviewWrite/ReviewInput.tsx
후기 제목, 내용, 사진 업로드 기능
후기 Path에 postId 추가
- src/store/reviewStore.ts
후기스토어 추가
> [feat]: 후기 작성 기능 구현

- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/mocks/mockData.ts
depositId params에서 불러오기로 수정
- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
로컬 저장방식 삭제, 백엔드에서 params에 담아서 보내주기로 수정함
> [fix] : depositId params에서 불러오기로 수정

- src/Components/RecruitDetail/Buttons/EditBtn.tsx
- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/Components/RecruitDetail/TripCost.tsx
- src/Components/RecruitDetail/TripHostProfile.tsx
- src/Components/RecruitDetail/TripItinerary.tsx
- src/Page/RecruitDetail.tsx
- src/mocks/paymentHandlers.ts
백엔드 서버 연동 부분 수정
- src/Components/RecruitDetail/TripHostProfile.tsx
테스트 데이터가 아닌 서버 연동으로 수정
> [fix] : 백엔드 서버 연동 부분 수정

- src/Components/Post.tsx
- src/Page/Recruitment.tsx
후기 글 목록 파일 불러오기 수정
후기 글 목록 파일 불러오기 수정
> [fix] 후기 및 모집 글 목록 페이지 로딩 에러 수정

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/SignUpForm.tsx
- src/Utils/apiFetch.ts
- src/mocks/fileHandler.ts
- src/mocks/handlers.ts
- src/mocks/mockData.ts
- src/mocks/profileHandlers.ts
- src/store/profileStore.ts
- ProfileCreate
프로필 생성 컴포넌트
- apifetch
파일 업로드 관련 api 처리 코드 수정
> [feat] 프로필 생성 기능 구현 및 파일 업로드 관련 api 처리 코드 수정

- src/Components/RecruitDetail/RecruitmentHeader.tsx
모집 게시글에서 현재 참여중인 인원 api 추가
- 현재 참여중인 인원 불러오기 기능 추가
> [fix] : 모집 게시글에서 현재 참여중인 인원 api 추가

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Utils/apiFetch.ts
- src/store/profileStore.ts
> [fix] 파일 업로드 형식 수정 및 프로필 수정 기능 수정

- src/Components/RecruitDetail/RecruitmentHeader.tsx
참여자 데이터 타입 정의 및 API 응답 타입 수정
- src/Components/RecruitDetail/RecruitmentHeader.tsx
> [fix]: 참여자 데이터 타입 정의 및 API 응답 타입 수정

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Sidebar.tsx
- src/Components/RecruitDetail/Buttons/EditBtn.tsx
- src/Page/Review.tsx
- src/Page/ReviewDetail.tsx
- src/Utils/postImgUrl.ts
- src/store/profileStore.ts
- MyProfile, ProfileEdit, Sidebar
정상적으로 이미지 표시되도록 로직 수정
- postImgUrl
미리보기 이미지 로직
> [fix] 서버 연동 테스트 후 코드 수정 및 이미지가 정상적으로 표시되도록 로직 수정

- src/Components/ReviewWrite/ReviewEdit.tsx
- src/Page/ReviewDetail.tsx
- src/Router/routes.tsx
- src/mocks/reviewHandlers.ts
리뷰 수정 페이지 작성
- src/Components/ReviewWrite/ReviewEdit.tsx
리뷰 수정 페이지 작성
- src/Page/ReviewDetail.tsx
리뷰 수정 path 변경
- src/mocks/reviewHandlers.ts
오류 코드 삭제
> [feat]: 리뷰 수정 페이지 작성

- src/Components/Post.tsx
- src/Components/ReviewWrite/RecruitInfo.tsx
- src/Components/ReviewWrite/ReviewEdit.tsx
- src/Components/ReviewWrite/ReviewInput.tsx
- src/Page/ReviewDetail.tsx
- src/Router/routes.tsx
- src/mocks/mockData.ts
- src/store/reviewPost.ts
후기 작성에서 이미지 api 연결 및 후기 디테일 페이지 path 변경
후기 디테일 페이지 path 수정
- src/Components/ReviewWrite/RecruitInfo.tsx
- src/Components/ReviewWrite/ReviewEdit.tsx
- src/store/reviewPost.ts
파일명 변경
- src/Components/ReviewWrite/ReviewInput.tsx
이미지 저장 및 미리보기 엔드포인트 연결
- src/Page/ReviewDetail.tsx
오류 코드 수정
> [fix]: 후기 작성에서 이미지 api 연결 및 후기 디테일 페이지 path 변경

- src/Page/Recruitment.tsx
- src/Page/Review.tsx
무한 스크롤 수정 및 데이터 유지
- src/Page/Recruitment.tsx
- src/Page/Review.tsx
무한 스크롤 수정 및 데이터 유지
> [refactor] 모집 글, 후기 글 목록 page 무한 스크롤 useInfiniteScroll 변경 및 기존 데이터 유지

- src/Components/ReviewWrite/RecruitInfo.tsx
국가명 mappingCountry utils 사용
- src/Components/ReviewWrite/RecruitInfo.tsx
> [refactor]: 국가명 mappingCountry utils 사용

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Page/ReviewDetail.tsx
- src/mocks/participationHandlers.ts
> [feat] 내가 작성한 후기 조회 및 여행 완료 상태일 때만 모집글 조회

- src/Components/Post.tsx
- src/Page/Community.tsx
- src/Page/Review.tsx
- src/Utils/apiFetch.ts
- src/mocks/communityHandlers.ts
- src/mocks/handlers.ts
- src/mocks/mockData.ts
커뮤니티 글 목록 완성
- src/Page/Community.tsx
커뮤니티 post 추가
- src/mocks/communityHandlers.ts
- src/mocks/handlers.ts
- src/mocks/mockData.ts
커뮤니티 MSW 추가
> Feat/커뮤니티 글 목록

- src/Components/CommunityWrite/CommunityEdit.tsx
- src/Components/CommunityWrite/CommunityInput.tsx
- src/Page/CommunityForm.tsx
- src/Router/routes.tsx
- src/store/communityPostStore.ts
- src/Components/CommunityWrite/CommunityEdit.tsx
커뮤니티 글 수정하기 기능 추가
- src/Components/CommunityWrite/CommunityInput.tsx
- src/Page/CommunityForm.tsx
커뮤니티 글 작성 페이지 추가
커뮤니티 글 작성 및 수정 라우트 추가
- src/store/communityPostStore.ts
커뮤니티 글 작성 관련 스토어 추가
> Feat/post write 커뮤니티 글 작성 및 수정 기능 추가

- src/Components/ReviewWrite/ReviewInput.tsx
스토어명 오류부분 수정
- src/Components/ReviewWrite/ReviewInput.tsx
> [fix]: 스토어명 오류부분 수정

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/Voting.tsx
- src/Components/Mypage/Sidebar.tsx
- src/Router/routes.tsx
- src/mocks/handlers.ts
- src/mocks/mockData.ts
- src/mocks/votingHandler.ts
- src/store/profileStore.ts
- MyVoting
투표 조회
- Voting
투표 기표 모달
> [feat] 투표 확인 탭 추가 및 투표 생성 

- src/Components/Post.tsx
- src/Components/RecruitWrite/Btn/PaymentBtn.tsx
- src/Utils/apiFetch.ts
> [fix] 포스트 에러 수정 및 결제하기 버튼 수정

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/SideComponents/Voting.tsx
- src/Components/Mypage/Sidebar.tsx
- src/mocks/votingHandler.ts
생성된 투표 조회 및 투표 기표 기능
MyVoting, Voting
- 투표 조회 / 투표 모달
> [feat] 생성된 투표 조회 및 투표 기표 기능

- src/Components/RecruitWrite/Btn/PaymentBtn.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
> [feat]: 게시글 등록 후 결제하기 버튼 구현

- src/Components/Post.tsx
- src/Page/Community.tsx
- src/Page/CommunityDetail.tsx
- src/Page/Recruitment.tsx
- src/Page/Review.tsx
- src/Router/routes.tsx
- src/mocks/mockData.ts
[feat] 커뮤니티 글 세부 페이지 완성
사진 불러오기 수정 (함수 -> url로)
- src/Page/CommunityDetail.tsx
커뮤니티 세부 글 페이지
커뮤니티 세부 글 페이지 링크 추가
- src/mocks/mockData.ts
커뮤니티 타입 수정
> [feat] 커뮤니티 글 세부 페이지 완성

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Sidebar.tsx
> [etc] 이미지 미리보기 코드 수정

- src/Components/Post.tsx
- src/Components/RecruitWrite/BasicInfo/TravelDateSelect.tsx
- src/Components/RecruitWrite/CrewCondition/Age.tsx
- src/Components/RecruitWrite/ExpectMoney/AccommodationFee.tsx
- src/Components/RecruitWrite/ExpectMoney/AirplaneFee.tsx
- src/Components/RecruitWrite/ExpectMoney/OtherExpenses.tsx
- src/Page/ReviewDetail.tsx
- src/store/recruitPostStore.ts
모집 글 페이지 수정 및 커뮤니티 세부 페이지 서버 연동
- 모집 글 작성 시 오늘 이전 날짜 선택 불가능하게 수정
- 커뮤니티 세부 페이지 서버 연동
> Fix/모집 글 페이지

- src/store/profileStore.ts
> [feat] age도 전역 상태로 저장

- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/Components/RecruitDetail/JoinAndPay.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Hooks/usePayment.ts
- src/Hooks/usePaymentFlow.ts
- src/Page/PaymentPage.tsx
- src/Page/PaymentResultPage.tsx
- src/Router/routes.tsx
- src/assets/icons/arrow_back.svg
- src/assets/icons/check.svg
결제 안내 및 결제 승인 페이지 구현
- src/Components/RecruitDetail/JoinAndPay.tsx
- src/Page/PaymentPage.tsx
결제 진행 페이지 별도 구현
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
결제 진행 페이지 이동 로직 추가
- src/Hooks/usePayment.ts
- src/Hooks/usePaymentFlow.ts
참여하기, 결제준비, 결제승인 훅 추가, 상황에 맞는 결제 flow훅 추가
- src/Page/PaymentResultPage.tsx
결제승인 페이지 별도 구현, 모집글 새로 생성 시 post 상태 변경을 위한 중간 페이지
> [feat]: 결제 안내 및 결제 승인 페이지 구현

- src/Components/Layout/HomeLayout.tsx
- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Post.tsx
- src/Components/RecruitDetail/RecruitmentHeader.tsx
- src/Components/RecruitWrite/Btn/CancelBtn.tsx
- src/Components/RecruitWrite/Btn/ResetBtn.tsx
- src/Components/SignInForm.tsx
- src/Page/RecruitDetail.tsx
- src/Page/SignIn.tsx
- src/Page/SignUp.tsx
- tailwind.config.js
> [style]: 버튼 디자인 통일 및 상태별 스타일 수정

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/Voting.tsx
- MyCompletedTrips
다녀온 여행들 목록 조회 -> 평점주기/후기작성
- MyVoting, Voting
투표 기표 창 열기 및 투표 기표 기능
> [feat] 다녀온 여행들 목록 조회 및 투표 기표 구현

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Utils/apiFetch.ts
> [feat] refresh 토큰 쿠키에 저장

- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/Components/RecruitDetail/RecruitmentHeader.tsx
- src/Page/RecruitDetail.tsx
상태에 따른 버튼 비활성화
- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/Components/RecruitDetail/RecruitmentHeader.tsx
- src/Page/RecruitDetail.tsx
> [refactor]: 상태에 따른 버튼 비활성화

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/Components/Mypage/SideComponents/Voting.tsx
- src/Components/Mypage/Sidebar.tsx
- src/Page/ReviewDetail.tsx
- src/store/profileStore.ts
> [fix] 서버 테스트 후 코드 수정

- src/Components/Common/Header.tsx
- src/Components/Layout/index.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Components/RecruitWrite/CrewCondition/Age.tsx
- src/Components/RecruitWrite/Preview.tsx
- src/Page/RecruitWrite.tsx
- src/Page/ReviewDetail.tsx
- src/Utils/apiFetch.ts
> fix/연동 테스트 수정

- src/Components/CommunityWrite/CommunityEdit.tsx
- src/Components/ReviewWrite/ReviewEdit.tsx
> [refactor]: 쿼리키 목록과 동일하게 수정

- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Page/Community.tsx
- src/Page/CommunityDetail.tsx
- src/Page/Recruitment.tsx
- src/Page/Review.tsx
- src/Page/ReviewDetail.tsx
[refactor] 각 행동에 대한 Alert 추가 및 에러 메시지 추가
- Alert 추가
-에러 메시지 추가
> [refactor] 각 행동에 대한 Alert 추가 및 에러 메시지 추가

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/RecruitDetail/TripDetails.tsx
- src/store/authStore.ts
> [fix] 테스트 후 코드 수정

- src/Components/Post.tsx
- src/Page/ReviewDetail.tsx
[fix] Post 투표중 수정 및 리뷰 디테일 페이지 undefined 수정
Poist 투표중 수정
- src/Page/ReviewDetail.tsx
리뷰 디테일 페이지 undefined 수정
> [fix] Post 투표중 수정 및 리뷰 디테일 페이지 undefined 수정

- src/store/authStore.ts
> [fix] 토큰 재발급 전에 기존 토큰 삭제

- src/App.tsx
- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/Components/Mypage/SideComponents/PasswordChangeModal.tsx
- src/Utils/apiFetch.ts
- src/store/authStore.ts
- src/store/profileStore.ts
29분마다 토큰 재발급 기능 및 작성한 모집글 목록 조회 조건 변경
버튼 색상 변경
- apiFetch
fetchCall함수 사용 시 최신 토큰을 헤더에 추가
- authStore 
언마운트 시 Interval 제거
> [feat] 29분마다 토큰 재발급 기능 및 작성한 모집글 목록 조회 조건 변경

- src/Utils/apiFetch.ts
- src/store/authStore.ts
> [fix] 에러 코드 수정

- src/Components/RecruitDetail/TripDetails.tsx
- src/Components/RecruitWrite/BasicInfo/DestinationSelect.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
[fix] 모집 글 작성 대륙-국가 선택 부분 코드 수정
- src/Components/RecruitDetail/TripDetails.tsx
- src/Components/RecruitWrite/BasicInfo/DestinationSelect.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
모집 글 작성 대륙, 국가 한글 <-> 국가 코드로 변경
> [fix] 모집 글 작성 대륙-국가 선택 부분 코드 수정

- src/Components/Layout/HomeLayout.tsx
- src/Components/RecruitDetail/TripDetails.tsx
- src/Components/RecruitDetail/TripHostProfile.tsx
- src/Components/RecruitDetail/TripItinerary.tsx
- src/Components/RecruitWrite/TravelPlan.tsx
- src/Components/SignInForm.tsx
- src/Components/SignUpForm.tsx
- src/Page/PaymentResultPage.tsx
전체 디자인 점검 및 수정
- 버튼 디자인 수정
- 사용자 프로필 사진 불러오기 수정
- 모집글 세부페이지 layout 수정
- 그외 텍스트 색상 수정
> [layout] : 전체 디자인 점검 및 수정

- src/Components/Post.tsx
- src/Page/PaymentResultPage.tsx
포스트 박스에 round 주기
- 후기 및 커뮤니티 post box round 전부 추가
> [layout]: 포스트 박스에 round 주기

- src/Components/Mypage/ProfileEdit.tsx
성별 안바뀌는 오류 수정
- profileEdit
성별 안바뀌는 오류 수정
> [fix] 성별 안바뀌는 오류 수정

- package-lock.json
- src/Components/Post.tsx
- src/Components/RecruitWrite/CrewCondition/Age.tsx
- src/Components/RecruitWrite/Preview.tsx
- src/Page/CommunityDetail.tsx
- src/Page/PaymentResultPage.tsx
> [fix] 디자인 수정

- src/Components/FindForm.tsx
- src/Components/SignInForm.tsx
- src/Page/Find.tsx
> [refactor]: 비밀번호 오류 에러메세지 수정

- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/store/authStore.ts
9분마다 토큰 재발급 및 만료시간 추가
디자인 수정
- authStore
9분마다 토큰 재발급하는 코드로 수정 및 만료시간 추가
> [feat] 9분마다 토큰 재발급 및 만료시간 추가

- src/Components/SignInForm.tsx
> [refactor]: 중복 코드 삭제

- package-lock.json
- package.json
- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/PasswordChangeModal.tsx
- src/mocks/mockData.ts
- src/mocks/participationHandlers.ts
디자인 변경
- Rating
평점을 별점 시스템 UI로 변경
- MyTravelJoin
투표중 상태일 때 취소 버튼 삭제
- PasswordChangeModal
비밀번호 변경 모달 UI 변경
- MyProfile
프로필 체크 후 없을 시 프로필 생성 컴포넌트로 이동
> [layout] 디자인 변경

- src/Components/RecruitDetail/RecruitmentHeader.tsx
> [layout]: 모집상태 버튼 이벤트 삭제

- src/mocks/mockData.ts
- src/type/types.ts
> [refactor] type 파일 분리

- src/apis/user.ts
- src/type/types.ts
api 호출 코드 분리
- apis/user
api 호출 코드 분리
> [refator] api 호출 코드 분리

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Sidebar.tsx
- src/Hooks/userQueries.ts
- src/apis/user.ts
- src/store/profileStore.ts
- src/type/types.ts
react-query 사용해서 프로필 및 회원 정보 서버 데이터 관리
react-query 사용해서 프로필 및 회원 정보 서버 데이터 관리
> [refactor] react-query 사용해서 프로필 및 회원 정보 서버 데이터 관리

- src/Components/RecruitDetail/TripHostProfile.tsx
- src/Components/RecruitDetail/TripItinerary.tsx
> [etc]: 프로필 기본 이미지 수정

- src/Components/Post/ReviewPost.tsx
- src/Page/ReviewDetail.tsx
- src/mocks/mockData.ts
- src/mocks/reviewHandlers.ts
- src/type/types.ts
이미지 불러오기 에러시 기본 이미지 설정 및 API 명세 변경에 따른 코드 변경
- src/Components/Post/ReviewPost.tsx
- src/Page/ReviewDetail.tsx
- src/mocks/mockData.ts
- src/mocks/reviewHandlers.ts
- src/type/types.ts
API 명세서에 mbti, 작성자, 작성자 프로필 이미지 추가에 따른 코드 변경
기본 이미지 설정
> [reactor] 리뷰 관련 리팩토링

- src/Components/Post/CommunityPost.tsx
- src/Components/RecruitWrite/Plan/TravelDay.tsx
- src/mocks/userHandlers.ts
- src/type/types.ts
커뮤니티 Post undefined 설정 및 모집 글 작성 collapse 추가
- src/Components/Post/CommunityPost.tsx
커뮤니티 Post undefined 설정
- src/Components/RecruitWrite/Plan/TravelDay.tsx
모집 글 작성 collapse 추가
> [fix] 리팩토링 후 백엔드 연동 test 수정

- src/Components/FindForm.tsx
- src/Components/RecruitDetail/RecruitmentHeader.tsx
- src/Components/RecruitDetail/TripHostProfile.tsx
- src/Components/ReviewWrite/ReviewEdit.tsx
- src/Components/SignInForm.tsx
- src/Components/SignUpForm.tsx
- src/Constants/message.ts
- src/Hooks/usePayment.ts
- src/Page/PaymentResultPage.tsx
- src/Page/RecruitDetail.tsx
- src/apis/participation.ts
- src/type/types.ts
모집글 상세페이지 api 분리
- src/Components/RecruitDetail/RecruitmentHeader.tsx
- src/Components/RecruitDetail/TripHostProfile.tsx
> [refactor]: 모집글 상세페이지 api 분리

- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/SideComponents/DeleteAccountModal.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/Components/Mypage/SideComponents/PasswordChangeModal.tsx
- src/Components/Mypage/Sidebar.tsx
- src/apis/user.ts
계정 관련 api 분리 및 마이페이지 리펙토링
- DeleteAccount, EmailChangeModal, PasswordChangeModal
api 분리
- MyProfile, ProfileCreate
흡연, 성별 상태관리 코드 변경
> [refactor] 계정 관련 api 분리 및 마이페이지 리펙토링

- src/Components/RecruitWrite/CrewCondition.tsx
- src/mocks/profileHandlers.ts
api 형식 수정
- src/Components/RecruitWrite/CrewCondition.tsx
profileData -> .data로 불러오기 변경
- src/mocks/profileHandlers.ts
.data 추가
> [fix] api 형식 수정

- src/Components/RecruitWrite/CrewCondition.tsx
- src/Utils/apiFetch.ts
유저 정보 불러오기 수정에 따른 모집 글 작성 수정
- src/Components/RecruitWrite/CrewCondition.tsx
.data 제거
> [fix] 유저 정보 불러오기 수정에 따른 모집 글 작성 수정

- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/Rating.tsx
- src/Utils/apiFetch.ts
> [refactor] 불필요한 코드 제거

- src/App.tsx
- src/store/authStore.ts
토큰 재발급 29분마다 실행 및 불필요한 코드 제거
- authStore
토큰 재발급 29분마다 실행 및 불필요한 코드 제거
> [refactor] 토큰 재발급 29분마다 실행 및 불필요한 코드 제거

- src/Components/RecruitDetail/JoinAndPay.tsx
- src/Components/RecruitDetail/RecruitmentHeader.tsx
- src/Components/RecruitDetail/TripHostProfile.tsx
- src/Components/SignUpForm.tsx
- src/Page/CommunityForm.tsx
- src/Page/PaymentPage.tsx
- src/Page/PaymentResultPage.tsx
- src/Page/RecruitDetail.tsx
- src/Page/Recruitment.tsx
- src/Page/ReviewForm.tsx
- src/Page/SignIn.tsx
- src/apis/auth.ts
- src/type/types.ts
참여자 정보 보기 기능 추가
- 참여인원수 클릭 시 참여자 정보 보기 모달창 띄우기(프로필, 닉네임, mbti 확인 가능)
> [feat]: 참여자 정보 보기 기능 추가

- src/Components/Mypage/MyAccountSettings.tsx
- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyProfile.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/DeleteAccountModal.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/Components/Mypage/SideComponents/PasswordChangeModal.tsx
- src/Components/Mypage/SideComponents/Voting.tsx
- src/Components/RecruitDetail/TripDetails.tsx
- src/Components/RecruitDetail/TripItinerary.tsx
- src/Components/RecruitWrite/ExpectMoney.tsx
- src/Components/RecruitWrite/RecruitForm.tsx
- src/Components/RecruitWrite/TravelPlan.tsx
- src/Page/RecruitDetail.tsx
> [refactor]: 폴더명 소문자로 통일

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/MyVoting.tsx
- src/Components/Mypage/ProfileCreate.tsx
- src/Components/Mypage/ProfileEdit.tsx
- src/Components/Mypage/Rating.tsx
- src/Components/Mypage/SideComponents/DeleteAccountModal.tsx
- src/Components/Mypage/SideComponents/EmailChangeModal.tsx
- src/Components/Mypage/SideComponents/PasswordChangeModal.tsx
- src/Components/Mypage/SideComponents/Voting.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Components/RecruitWrite/Plan/TravelDay.tsx
- src/Page/Community.tsx
- src/Page/CommunityDetail.tsx
- src/Page/Recruitment.tsx
- src/Page/Review.tsx
- src/Page/ReviewDetail.tsx
[chore] 폴더 파스칼케이스 -> 스네이크케이스로 변경
> [chore] 폴더 파스칼케이스 -> 스네이크케이스로 변경

- src/Router/routes.tsx
마이페이지 관련 url 변경
- router
마이페이지 관련 url 변경
> [refactor] 마이페이지 관련 url 변경

- src/Components/Post/ReviewPost.tsx
- src/Components/RecruitWrite/BasicInfo/RegionInput.tsx
- src/Components/RecruitWrite/BasicInfo/TravelDateSelect.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Components/RecruitWrite/Plan/DayDetail.tsx
- src/Components/RecruitWrite/Plan/TravelDay.tsx
- src/Page/RecruitDetail.tsx
- src/Utils/convertContinentName.ts
- src/Utils/getFilterParams.ts
- src/store/recruitPostStore.ts
모집 글 작성 시 zustand 데이터만 사용하도록 수정
- src/Components/Post/ReviewPost.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Utils/convertContinentName.ts
- src/Utils/getFilterParams.ts
변수 이름 변경 (getContinentName -> convertContinentName)
- src/Components/RecruitWrite/BasicInfo/RegionInput.tsx
- src/Components/RecruitWrite/BasicInfo/TravelDateSelect.tsx
- src/Components/RecruitWrite/Plan/DayDetail.tsx
- src/Components/RecruitWrite/Plan/TravelDay.tsx
- src/Utils/getFilterParams.ts
zustand 사용으로 수정
> [refactor] 모집 글 작성 시 zustand 데이터만 사용하도록 수정

- src/Components/Common/Modal.tsx
React Portal을 사용해 모달 컴포넌트를 body의 최상위에 렌더링
- React Portal을 사용
> [fix] 모달 컴포넌트 body의 최상위에 렌더링

- src/Components/RecruitDetail/Buttons/JoinBtn.tsx
- src/Hooks/usePayment.ts
참여하기 버튼 클릭 시 에러 메세지 모달 알림 로직 추가
- 기존 alert 메시지를 모달 컴포넌트로 대체
- 서버에서 전달받은 에러 메시지를 모달로 표시하도록 수정
- useParticipation 훅에서 모달 상태 관리하도록 개선
> [refactor]: 참여하기 버튼 클릭 시 에러 메세지 모달 알림 로직 추가

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyTravelHistory.tsx
- src/Components/Mypage/MyTravelJoin.tsx
- src/Components/Mypage/ProfileEdit.tsx
국가 표기 스타일 수정 및 프로필 수정 과정 중 profileData를 Zustand로 전역 상태 관리 추가
- ProfileEdit
프로필 수정 성공 시 profileData를 Zustand로 전역 상태 관리 추가
- MyCompletedTrips, MyTravelJoin, MyTravelHistory
국가 표기 스타일 수정
> [refactor] 국가 표기 스타일 수정 및 프로필 수정 과정 중 profileData를 Zustand로 전역 상태 관리 추가

- src/Components/RecruitDetail/TripHostProfile.tsx
- src/Components/ReviewWrite/RecruitInfo.tsx
- src/Components/ReviewWrite/ReviewEdit.tsx
- src/Components/ReviewWrite/ReviewInput.tsx
- src/store/reviewPostStore.ts
- src/type/types.ts
서버 응답값 변경으로 한글 수정 로직 삭제
- 성별 실제 응답값 한글 변경으로 기존 변환 로직 삭제
- 국가 실제 응답값 한글 변경으로 기존 변환 로직 삭제
> [fix]: 성별 한글 수정 로직 삭제

- src/Components/Mypage/MyCompletedTrips.tsx
- src/Components/Mypage/MyRecruitment.tsx
- src/Page/CommunityDetail.tsx
서버 테스트 후 에러 수정 및 스타일 변경
- CommunityDetail.tsx
커뮤니티 글 삭제 시 알림 모달창이 안뜨는 현상 수정
- MyCompletedTrips.tsx, MyRecruitment.tsx
국가 표기 스타일 수정
> [fix] 서버 테스트 후 수정 작업

- src/Components/ReviewWrite/ReviewEdit.tsx
- src/Components/ReviewWrite/ReviewInput.tsx
> [fix]: 대륙 및 국가 formData 영문으로 수정

- src/App.tsx
- src/Components/Layout/HomeLayout.tsx
- src/Components/RecruitWrite/Btn/SubmitBtn.tsx
- src/Components/ReviewWrite/ReviewInput.tsx
- src/Hooks/useInfinityFetch.ts
- src/Page/CommunityDetail.tsx
- src/Page/ReviewDetail.tsx
- src/Utils/convertContinentName.ts
- src/Utils/getFilterParams.ts
- src/apis/fetchCall.ts
- src/mocks/communityHandlers.ts
[fix] queyKey 달라서 refetch 안되는 오류 수정
기존 queryKey 수정을 통한 글 등록, 삭제, 수정 시 데이터 새로 고침 실행
> [fix] queyKey 달라서 refetch 안되는 오류 수정

- src/Components/Mypage/ProfileEdit.tsx
프로필 수정 후 즉각적인 동기화를 위해 URL을 다시 로드하는 코드 추가.
- ProfileEdit
즉각적인 동기화를 위해 URL을 다시 로드하는 코드 추가.
> [refactor] 즉각적인 동기화를 위해 URL을 다시 로드하는 코드 추가.
